### ISSUE TITLE
Video not exported

### ISSUE THREAD

**Issue by somebrickfilmer** [TahomaDigital/Arlo#1]
when i click the export video, popup says Creating Video - Please Wait. and..nothing!
What should I do?

p.s Oh, this happened while I was using the portable version, so even though I installed the latest version, this happens.

**Comment by jeremybullock** [comment]
Have you checked your desktop?  That is the default location for exported videos.  I'm going to make it choosable in the next version.

**Comment by somebrickfilmer** [comment]
I don't know what the error was, but I tried it again with the latest release and it worked.
this software is so awesome!! I always use this software when making my videos. Keep it up

**Comment by jeremybullock** [comment]
Thank you!  Glad to hear it!
